### PR TITLE
Update boxes

### PR DESCRIPTION
**Pull request by njam**
- Update serverspec from 1 to 2 (2f2c86c)
- Simplify packer provisioning by configuring *password-less sudo* already during Debian installation
- Reduce disk size from 250G to 30G
- Update gem dependencies, update puppet modules
- Update Debian source AMI and ISO image

### CODE REVIEW

**Comment by njam** [comment]
@kris-lab @ppp0 please review
See summary of changes in the ticket description. I recommend to look at the changes commit by commit.

I have successfully built new boxes with this branch, the specs succeed.
Once you give me the go ahead I will release them.

**Comment by njam** [comment]
...btw, comparing VM performance by running `time bin/phpunit` in an SK project provisioned to EC2:

Current release AMI (ami-e40ca493), using *Paravirtual/PV* virtualization on an *m3.large* instance:
```
Time: 9.78 minutes, Memory: 256.50Mb

OK, but incomplete, skipped, or risky tests!
Tests: 1229, Assertions: 5484, Skipped: 1.
```

Pre-release AMI from this pull request (ami-9753d3e0), using *HVM* virtualization on an *m3.large* instance:
```
Time: 6.08 minutes, Memory: 256.50Mb

OK, but incomplete, skipped, or risky tests!
Tests: 1229, Assertions: 5484, Skipped: 1.
```

Pre-release AMI from this pull request (ami-9753d3e0), using *HVM* virtualization on an *c4.8xlarge* instance:
```
Time: 7.94 minutes, Memory: 256.25Mb

OK, but incomplete, skipped, or risky tests!
Tests: 1229, Assertions: 5484, Skipped: 1.

```

All runs use an EBS device with 1000 IOPS. Changing to 4000 IOPS did not bring any changes.

**Comment by njam** [comment]
Pair-reviewed with Philipp

**Comment by njam** [comment]
@kris-lab could you review the last commit (821e4eb3cfb93aa9d2da5d188669cba8a682b261)?
Now the version order is defined, and the last one is the newest (youngest).

**Comment by kris-lab** [comment]
sgtm

**Comment by njam** [comment]
Boxes released

**Pull request merged**
