### PR TITLE
Create new boxes with Virtualbox 5

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@ppp0 please review

**Comment by ppp0** [comment]
I do not completely understand this PR.. Were you assembling a box that is *compatible* with Virtualbox 5?

**Comment by ppp0** [comment]
Or *using* Virtualbox 5 as the "assembler"?

**Comment by njam** [comment]
I'm creating new boxes with:
- New puppet modules
- New Debian AMIs
- Virtualbox 5 guest additions (virtualbox only)

**Comment by ppp0** [comment]
Oh, now it is clear.. well LGTM - I reckon you have a tested enviroment in front of you

**Comment by njam** [comment]
Release to atlas

**Pull request merged**
