### PR TITLE
Update boxes (including janus)

### PR DESCRIPTION
**Pull request by njam**

### CODE REVIEW

**Comment by njam** [comment]
@tomaszdurka please have a look at ae1e358f33f3dbfd4d116306a03dd2d2fdae6bc0

Unfortunately I don't see a good way to install `cm_janus` - it needs a lot of app-specific configuration.
Can we make all of those optional, and in that case skip a few resources, but still install the cm-janus service?

**Comment by njam** [comment]
Preferably we'll include `cm::services::janus` without args

**Comment by njam** [comment]
Waiting for https://github.com/cargomedia/puppet-packages/pull/1011

**Comment by tomaszdurka** [comment]
Looks good.

**Comment by njam** [comment]
released

**Pull request merged**
