### PR TITLE
Add Debian Jessie (8)

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review, build and specs successful

Also built: `debian-7-adm64-cm`

Will publish after merge

**Comment by njam** [comment]
- plain.json,default.json: Not sure if it's worth having this "variables" block - how about just inlining? They are used only once, and "fullname" is not used anywhere.
- plain.json,default.json,preseed.cfg: Shouldn't we stick to the canonical download URL for the image (`http://cdimage.debian.org/debian-cd/8.3.0/arm64/iso-cd/debian-8.3.0-arm64-netinst.iso`) and apt to be geo-agnostic? Or maybe use https://wiki.debian.org/DebianGeoMirror ?
- preseed.cfg: we don't set the the domain like in the other boxes (`d-i netcfg/get_domain string vagrantup.com`). On purpose?
- base.sh: Backport this `export DEBIAN_FRONTEND=noninteractive` also to ubuntu?
- base.sh: upgrade: I think we can just use `confnew` (and not `confdef`), because this is a *new* box

**Comment by ppp0** [comment]
* ok
* ok
* Yes, on purpose. May be related to [this bug](https://bugs.launchpad.net/ubuntu/+source/netcfg/+bug/1452202) but I had the same issue and could solve it by [defining the domain name in the kernel boot parameters](https://github.com/cargomedia/vagrant-boxes/pull/61/files#diff-fc93a768cd483ab69c9e41c8059aae76R15)
* if it does not hurt.. :) - and to debian 7? I understand the problem was `grub` wanting to update and some `/etc/default/grub` that is not covered by those `confold` and `confnew` (see [this discussion](http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt))
* agree

**Comment by njam** [comment]
afaiu `confnew` enforces there will be no interactivity. `confdef` *tries* to pick the right choice, so it's useful in combination with either `confold` or `confnew` to guarantee no interactivity. So `confnew` alone should be fine?
See also: http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt/262445#262445

IMO we don't need to backport everything to debian7, as we can hopefully deprecate it soonish.

**Comment by ppp0** [comment]
that's well possible, otoh setting the ENV variable got me rid of the problem, ok for Wheezy

**Comment by ppp0** [comment]
Took time to validate and remove the last glitches

@njam please review

**Comment by njam** [comment]
lgtm!

**Pull request merged**
