### PR TITLE
Include only common cm-janus/janus modules

### PR DESCRIPTION
**Pull request by tomaszdurka**

### CODE REVIEW

**Comment by tomaszdurka** [comment]
@njam or @kris-lab please review

**Comment by kris-lab** [comment]
lgtm

**Comment by njam** [comment]
lgtm
Still need to update puppet modules in the repo here.
I will take over and build boxes from this now.

**Comment by njam** [comment]
You pushed to upstream, will open new PR

**Comment by tomaszdurka** [comment]
Yes, cloning was taking ages, used web interface.

**Comment by njam** [comment]
ah :D

**Pull request closed without merging**
