### PR TITLE
Add ubuntu 15.04

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
:cry: 
[Same troubles](https://github.com/cargomedia/vagrant-boxes/pull/53#issuecomment-149931203) for the AMI built with
```
    {
      "name": "aws",
      "type": "amazon-ebs",
      "region": "eu-west-1",
      "source_ami": "ami-e38ab694",
      "instance_type": "m3.large",
      "ssh_username": "ubuntu",
      "ami_name": "ubuntu-1504-amd64-default {{timestamp}}",
      "ami_description": "https://github.com/cargomedia/vagrant-boxes",
      "ami_groups": ["all"],
      "ami_regions": ["us-east-1"],
      "ssh_timeout": "5m"
    }
```

```
[   56.393228] cloud-init[576]: Cloud-init v. 0.7.7 running 'init' at Wed, 21 Oct 2015 16:24:24 +0000. Up 56.25 seconds.

[   56.393383] cloud-init[576]: 2015-10-21 16:24:24,513 - util.py[WARNING]: Route info failed: Unexpected error while running command.

[   56.393513] cloud-init[576]: Command: ['netstat', '-rn']

[   56.393632] cloud-init[576]: Exit code: 1

[   56.393754] cloud-init[576]: Reason: -

[   56.393872] cloud-init[576]: Stdout: 'Kernel IP routing table\nDestination     Gateway         Genmask         Flags   MSS Window  irtt Iface\n'

[   56.393988] cloud-init[576]: Stderr: ''

[   56.608089] cloud-init[576]: ci-info: +++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++

[   56.608254] cloud-init[576]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+

[   56.608380] cloud-init[576]: ci-info: | Device |   Up  |  Address  |    Mask   | Scope |     Hw-Address    |

[   56.608501] cloud-init[576]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+

[   56.608621] cloud-init[576]: ci-info: |   lo   |  True | 127.0.0.1 | 255.0.0.0 |   .   |         .         |

[   56.608740] cloud-init[576]: ci-info: |   lo   |  True |  ::1/128  |     .     |  host |         .         |

[   56.608857] cloud-init[576]: ci-info: |  eth0  | False |     .     |     .     |   .   | 22:00:0a:60:1d:17 |

[   56.608973] cloud-init[576]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+

[   56.609090] cloud-init[576]: ci-info: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!Route info failed!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[   56.609207] cloud-init[576]: 2015-10-21 16:24:24,729 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [0/120s]: request error [('Connection aborted.', OSError(101, 'Network is unreachable'))]

```

I suspect our build scripts mess up networking somehow

**Comment by ppp0** [comment]
Network has troubles and `cloud-init` stops at (this step)[http://cloudinit.readthedocs.org/en/latest/topics/datasources.html#ec2]

**Comment by ppp0** [comment]
looks good now - doing a final build, test and publish

**Comment by njam** [comment]
- puppet.sh: adjust deb

**Comment by njam** [comment]
Rest looks good!

**Comment by ppp0** [comment]
All built, tested and vagrantcloud released
```
Releasing ubuntu-1504-default version 0.2.0...
Uploading virtualbox/ubuntu-1504-default-0.2.0.box to S3...
Uploading aws/ubuntu-1504-default-0.2.0.box to S3...
Creating Vagrant Cloud box ubuntu-1504-default version 0.2.0...
Releasing ubuntu-1504-plain version 0.2.0...
Uploading virtualbox/ubuntu-1504-plain-0.2.0.box to S3...
Uploading aws/ubuntu-1504-plain-0.2.0.box to S3...
Creating Vagrant Cloud box ubuntu-1504-plain version 0.2.0...
```

**Pull request merged**
