### PR TITLE
Build CM box for Jessie

### PR DESCRIPTION
**Pull request by ppp0**
Depends on https://github.com/cargomedia/sk/pull/3620

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
I talked with @njam yesterday about this... he mentioned, there are some (his custom one) helper scripts which are helpful for building the boxes. 

I have never built the box in person, however I would be glad if you guys would give me some intro.

**Comment by ppp0** [comment]
This is an easy topic...

There is a shell script which invokes the single build/test steps and then uploads the built boxes to atlas/AWS (and as such carries credentials)...

it looks like this:
```sh
export aws_key_id='blabla'
export aws_key_secret='secretblabla'

export vagrant_cloud_username='cargomedia'
export vagrant_cloud_access_token='lotsofrandomchars'

if (bundle exec rake confirm); then
    bundle exec rake build
    bundle exec rake spec
    bundle exec rake release
fi
```

Myself, I have a modified Rakefile so that I can select the type of box to be built (default is to build everything):
```ruby
[..]
desc 'Confirm procedure on selected boxes'
task :confirm do |t|
  def prompt(*args)
    print(*args)
    STDIN.gets
  end
  puts '**CAUTION** These boxes will be built:'
  environment.find_templates(template_name).each do |template|
    puts "\t- #{template.name} : #{builders ||template.builder_list}"
  end
  answer = prompt "\nDo you really want to proceed? (N/y)"
  exit(1) if answer !~ /y|Y/
end
[..]
````

**Comment by kris-lab** [comment]
Perfect! thanks

**Comment by njam** [comment]
Remember to update the puppet modules before building!
See docu here:
https://github.com/cargomedia/vagrant-boxes#development-building-and-uploading

**Comment by ppp0** [comment]
Boxes are built verified and uploaded... Happily merging

**Comment by njam** [comment]
Please add `Puppetfile.lock`

**Pull request merged**
