### PR TITLE
Change preseed mirror to httpredir, pre-install https transport

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review (I am still building the boxes, will take some time)

**Comment by njam** [comment]
👍

**Comment by njam** [comment]
You changed `puppet/Puppetfile`, but not the `Puppetfile.lock` - on purpose?

**Comment by ppp0** [comment]
@njam please review

I re-built and deployed following boxes:
- debian-7-amd64-cm for both s3 and virtualbox
- debian-8-amd64-plain and default for virtualbox
- debian-7-amd64-plain and default for virtualbox

please let me know if you think it makes sense to have more boxes (e.g. to s3) built and deployed. Will take some time...

**Comment by njam** [comment]
With "s3" you mean "aws"?
Yes, I think we should release all boxes for all providers. Otherwise can lead to confusion. Packer builds the same box for multiple providers in parallel, so it takes the same amount of time.

**Comment by njam** [comment]
- Rakefile: What is this "confirm" task for?
- cleanup-virtualbox.sh: do the same for debian 7?

**Comment by ppp0** [comment]
* Rakefile: it's used in my build script to confirm builds on selected machines. I will take it out and use it for myself. That regex in env var `templates` is related
* Will do

About packer's parallelism: I have not noticed I will have closer look next time when it's building.

**Comment by ppp0** [comment]
I thought again about 
>cleanup-virtualbox.sh: do the same for debian 7 (and ubuntu)?

I'm not fully ok with it for several reasons:
* It's not tested to be working on wheezy (vivid) yet -> time consuming
* Benefit unclear. Wheezy boxes are already way smaller than on Jessie
* Time Consuming
* Wheezy support lifetime about to expire

@njam wdyt?

**Comment by njam** [comment]
- Rakefile: don't remove `build`
- cleanup-virtualbox.sh: port also to ubuntu? mainly to not maintain different versions of a script doing the same in the future.

**Comment by ppp0** [comment]
* ohoh :)
* makes sense

**Comment by njam** [comment]
- Install "apt-transport-https" also for ubuntu?

rest lgtm

**Comment by ppp0** [comment]
@njam as feared (https://github.com/cargomedia/vagrant-boxes/pull/66#issuecomment-208993320) building an AMI on Ubuntu failed

**Comment by njam** [comment]
what happened?

**Comment by ppp0** [comment]
I don't have the logs anymore. Something about the swapon/swapoff on a non-existent drive.

**Comment by ppp0** [comment]
````
==> aws: Provisioning with shell script: scripts/cleanup-virtualbox.sh
    aws: Fill with 0 the swap partition to reduce box size
    aws: swapoff: /dev/disk/by-uuid: swapoff failed: Is a directory
==> aws: Terminating the source AWS instance...
==> aws: No AMIs to cleanup
==> aws: Deleting temporary security group...
==> aws: Deleting temporary keypair...
Build 'aws' errored: Script exited with non-zero exit status: 255
```

**Comment by ppp0** [comment]
I honestly don't think it's worth the effort of debugging it further

**Comment by njam** [comment]
Let's run this code only for virtualbox? I think it's only relevant there. The old script was guarded like this:
```sh
if test -f .vbox_version ; then
```

**Comment by ppp0** [comment]
@njam makes sense.. Now, all boxes are up-to-date (see https://atlas.hashicorp.com/cargomedia/boxes/)

**Comment by njam** [comment]
- cleanup-virtualbox.sh: Let's make all of these commands only run on virtualbox (the file is called cleanup-*virtualbox*, and I don't think this is relevant elsewhere?). Or is there any reason to run it on EC2 as well?
- cleanup-virtualbox.sh: Let's streamline the two scripts (guard against non-virtualbox)

**Comment by ppp0** [comment]
@njam agree to merge?

**Comment by njam** [comment]
lgtm

**Pull request merged**
