### PR TITLE
Upgrade vagrant boxes

### PR DESCRIPTION
**Pull request by ppp0**
Spec test boxes want to upgrade a few packages when issuing `apt-get update/upgrade`, among them the kernel

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by ppp0** [comment]
boxes are building and will be released soon

**Comment by njam** [comment]
Did you upgrade the puppet modules? Then `Puppetfile.lock` should be changed.

**Comment by ppp0** [comment]
I did a librarian-install, yes. At commit time, `Puppetfile.lock` dod not show up, though.
The current file is
````
-rw-r--r--   1 xxx  xxx  12816 Oct  6 12:15 Puppetfile.lock
```

checking if it's correct

**Comment by ppp0** [comment]
Cross-checked my Puppetfile with https://github.com/cargomedia/vagrant-boxes/blob/master/puppet/Puppetfile.lock

No diff. Is this expected?

**Comment by njam** [comment]
If there's no diff, then the modules have not been changed.
I think a `bundle exec librarian-puppet update` is needed! (readme should probably be updated too)

**Comment by ppp0** [comment]
Will do after lunch. What I did is check the `puppet/modules` folder (it was empty) and later on a 
```
cd puppet
bundle exec librarian-puppet install
```

According to the doc.

**Comment by njam** [comment]
`librarian-puppet install` installs the module that are defined in the lock file, so the old ones. To update modules and the Lockfile `update` is needed. I would suggest to change the readme to only mention `update`?

**Comment by ppp0** [comment]
@njam makes sense, please review

**Comment by njam** [comment]
lgtm

**Comment by njam** [comment]
Can you rebuild the boxes again (especially cm might be different)?

**Pull request merged**
